#!/bin/bash -xeu

root_dir="$(pwd)"
sarasa_dir="sarasa"
sarasa_nerd_dir="sarasa-nerd"
mkdir -p $sarasa_nerd_dir
cd $sarasa_nerd_dir
fix_xAvgCharWidth () {
  original_font=$1
  patched_font=$2

  ttx -o "$original_font.ttx" -t "OS/2" $original_font
  ttx -o "$patched_font.ttx" -t "OS/2" $patched_font

  original_x_avg_char_width="$(grep xAvgCharWidth "$original_font.ttx" | cut -d '"' -f 2)"
  echo original xAvgCharWidth is $original_x_avg_char_width
  rm -rf "$original_font.ttx"

  sed -i "" -E "s/xAvgCharWidth value=\"[0-9]+\"/xAvgCharWidth value=\"${original_x_avg_char_width}\"/g" \
    "$patched_font.ttx"

  ttx -o ${patched_font/.ttf/.after.ttf} -m $patched_font "$patched_font.ttx"
  rm -rf "$patched_font.ttx"
  rm $patched_font
  mv ${patched_font/.ttf/.after.ttf} $patched_font
}

for item in ../"$sarasa_dir"/*; do
  if [ -f "$item" ]; then
    extension="${item##*.}"
    if [ "$extension" == "ttf" ]; then
      echo "processing " "$item"
      ../font-patcher --quiet --adjust-line-height --complete --careful "$item"
      fix_xAvgCharWidth $item $(ls -t | head -1)
    fi
  fi
done

cd "$root_dir"
echo "list generated ttf"
ls $sarasa_nerd_dir/*.ttf

echo "generating ttc from ttf"
python otf2otc.py -o $sarasa_nerd_dir/SarasaTermSCNerd.ttc $sarasa_nerd_dir/SarasaTermSCNerd-*.ttf
cd "$sarasa_nerd_dir"
echo "creating tarball of ttf files"
COPYFILE_DISABLE=1 tar -czvf SarasaTermSCNerd.ttf.tar.gz SarasaTermSCNerd-*.ttf
echo "creating tarball of ttc files"
COPYFILE_DISABLE=1 tar -czvf SarasaTermSCNerd.ttc.tar.gz SarasaTermSCNerd.ttc
echo "creating 7zip of ttc files"
7zr a -mx9 SarasaTermSCNerd.ttc.7z SarasaTermSCNerd.ttc
echo "creating 7zip of ttf files"
7zr a -mx9 SarasaTermSCNerd.ttf.7z SarasaTermSCNerd-*.ttf
cd "$root_dir"
