name: Release

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:      

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: sudo apt update && sudo apt install -y fontforge python3-fontforge python3-fonttools p7zip jq

      - name: Download Sarasa Gothic
        run: |
          wget -q $(curl 'https://api.github.com/repos/be5invis/Sarasa-Gothic/releases' | jq -r '.[0].assets | map(.browser_download_url) | map(select(test("SarasaTermSC-TTF-[0-9.]+\\.7z"))) | .[0]')
          7zr x Sarasa*.7z
          mkdir sarasa
          mv Sarasa*.ttf sarasa

      - name: Download Font Patcher
        run: |
          wget -q https://github.com/ryanoasis/nerd-fonts/raw/refs/heads/master/FontPatcher.zip
          unzip FontPatcher.zip

      - name: Copy Scripts
        run: cp scripts/font-patcher font-patcher && cp scripts/otf2otc.py otf2otc.py

      - name: Build Nerd Font
        run: bash -xeu scripts/build

      - name: Display structure of the directory
        run: ls -R

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: ./sarasa-nerd/*{.gz,.7z}
          file_glob: true    
          name: Release ${{ steps.get_version.outputs.VERSION }}
          tag_name: ${{ steps.get_version.outputs.VERSION }}            
          draft: false
          prerelease: false 
      - name: Clear files
        run: |
          rm -rvf *.7z
          rm -rvf *.ttf
          rm -rvf sarasa
          rm -rvf sarasa-nerd

      - name: Download Sarasa Gothic Unhinted
        run: |
          wget -q $(curl 'https://api.github.com/repos/be5invis/Sarasa-Gothic/releases' | jq -r '.[0].assets | map(.browser_download_url) | map(select(test("SarasaTermSC-TTF-Unhinted-[0-9.]+\\.7z"))) | .[0]')
          7zr x Sarasa*.7z
          mkdir sarasa
          mv Sarasa*.ttf sarasa

      - name: Build Nerd Font
        run: bash -xeu scripts/build

      - name: Rename file
        run: |
          cd sarasa-nerd
          mv SarasaTermSCNerd.ttf.tar.gz SarasaTermSCNerd-Unhinted.ttf.tar.gz
          mv SarasaTermSCNerd.ttc.tar.gz SarasaTermSCNerd-Unhinted.ttc.tar.gz
          mv SarasaTermSCNerd.ttf.7z SarasaTermSCNerd-Unhinted.ttf.7z
          mv SarasaTermSCNerd.ttc.7z SarasaTermSCNerd-Unhinted.ttc.7z
          cd ..

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }} 
          file: ./sarasa-nerd/*{.gz,.7z}
          file_glob: true            
          name: Release ${{ steps.get_version.outputs.VERSION }}
          tag_name: ${{ steps.get_version.outputs.VERSION }}            
          draft: false
          prerelease: false             
